### ISSUE TITLE
How connect to sentinel from another PC 

### ISSUE THREAD

**Issue by nbxtruong** [itsmetommy/docker-redis4#1]
I have two machines are running on Ubuntu 18.04. First machine (IP: 192.168.1.7) run redis sentinel, and second (IP: 192.168.1.8) run nodejs application.

I don't know how to connect to Redis Sentinel on the second machine?

But, when I setup all of them on same machine. Everything work fine with this config:
{ sentinels: [ { host: "172.22.0.4", port: 26379 }, { host: "172.22.0.5", port: 26379 }, { host: "172.22.0.6", port: 26379 } ], name: "mymaster" }

**Comment by itsmetommy** [comment]
Try checking if the port is blocked using:
nc -vz 192.168.1.7 26379

It may be blocked by your Firewall.

**Comment by itsmetommy** [comment]
@NguyenBaoXuanTruong Any update on this?

**Comment by itsmetommy** [comment]
I'm going to go ahead and close this issue, being that there is nothing wrong with the actual code itself. Please email me if you have any other questions.
